require 'postmen/version'

# Require postmen modules
require 'postmen/carrier'
require 'postmen/carriers'
require 'postmen/common'
require 'postmen/address'
require 'postmen/dimension'
require 'postmen/item'
require 'postmen/parcel'
require 'postmen/shipment'
require 'postmen/invoice'
require 'postmen/service_option_general'
require 'postmen/service_option_insurance'
require 'postmen/service_option_cod'
require 'postmen/custom'
require 'postmen/create_label_base'